services:
  jellyfin-whatsapp:
    container_name: jellyfin-whatsapp
    image: jellyfin-whatsapp:${APP_VERSION:-latest}
    restart: unless-stopped

    build:
      context: .
      args:
        - APP_VERSION=${APP_VERSION}

    ports:
      - "8000:8000"
      - "3000:3000"

    shm_size: "1gb"

    volumes:
      - ./data:/data
      - ./config:/config

    environment:
      TZ: America/Argentina/Buenos_Aires
      PYTHONUNBUFFERED: "1"
      APP_VERSION: ${APP_VERSION}